include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_fields: true
    always_specify_types: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    unnecessary_this: true
    no_duplicate_case_values: true

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
