name: inget
description: "A simple note-taking app built with Flutter and Riverpod."
publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^13.0.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  clipboard: ^0.1.3 
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.6
  riverpod_generator: ^2.3.10
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true